### ISSUE TITLE
OSError: could not get source code

### ISSUE THREAD

**Issue by Elefant-Freeciv** [pypr/compyle#103]
The error message: `Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "/home/user/miniconda3/lib/python3.11/site-packages/compyle/parallel.py", line 573, in __call__
    self.elementwise(*args, **kwargs)
  File "/home/user/miniconda3/lib/python3.11/site-packages/compyle/profile.py", line 72, in wrapper
    return method(*args, **kwargs)
  File "/home/user/miniconda3/lib/python3.11/site-packages/compyle/jit.py", line 355, in __call__
    c_func = self._generate_kernel(*args)
  File "/home/user/miniconda3/lib/python3.11/site-packages/compyle/jit.py", line 29, in wrapper
    setattr(f, 'cached_kernel', {key_val: method(*args)})
  File "/home/user/miniconda3/lib/python3.11/site-packages/compyle/jit.py", line 341, in _generate_kernel
    declarations = helper.annotate()
  File "/home/user/miniconda3/lib/python3.11/site-packages/compyle/jit.py", line 160, in annotate
    src = dedent('\n'.join(getsourcelines(self.func)[0]))
  File "/home/user/miniconda3/lib/python3.11/site-packages/compyle/utils.py", line 13, in getsourcelines
    return inspect.getsourcelines(obj)
  File "/home/user/miniconda3/lib/python3.11/inspect.py", line 1244, in getsourcelines
    lines, lnum = findsource(object)
  File "/home/user/miniconda3/lib/python3.11/inspect.py", line 1081, in findsource
    raise OSError('could not get source code')
OSError: could not get source code`

Steps to reproduce: install compyle with pip (latest version from git) and run the default example.

**Comment by Elefant-Freeciv** [comment]
getfile(object) just before the error returns <string> instead of <path/to/file>

**Comment by Elefant-Freeciv** [comment]
Error is due to running file without saving first in Thonny. As such it is probably a bug in Thonny and not this project.
